export const VENDORS = [
  'WebKit', // Safari
  'Mozilla', // Firefox
  'Google Inc.', // Chrome
  'Microsoft', // IE
  'Opera', // Opera
]

export const UNMASKED_VENDORS = [
  '3672',
  'AMD',
  'ARM',
  'ATI Technologies Inc.',
  'Apple',
  'Apple Inc.',
  'Google Inc.',
  'Google Inc. (0x05404C42)',
  'Google Inc. (AMD)',
  'Google Inc. (ARM)',
  'Google Inc. (ATI Technologies Inc.)',
  'Google Inc. (Apple)',
  'Google Inc. (Google)',
  'Google Inc. (Imagination Technologies)',
  'Google Inc. (Intel Inc.)',
  'Google Inc. (Intel Open Source Technology Center)',
  'Google Inc. (Intel)',
  'Google Inc. (Mesa)',
  'Google Inc. (Mesa/X.org)',
  'Google Inc. (Microsoft Corporation)',
  'Google Inc. (Microsoft)',
  'Google Inc. (NVIDIA Corporation)',
  'Google Inc. (NVIDIA Corporation) #7pz9yksmUm',
  'Google Inc. (NVIDIA Corporation) #NbhL24LYfk',
  'Google Inc. (NVIDIA Corporation) #SoJg7htQt4',
  'Google Inc. (NVIDIA Corporation) #udEpwF086L',
  'Google Inc. (NVIDIA)',
  'Google Inc. (Qualcomm)',
  'Google Inc. (Qualcomm) #YVVCJhvoG6',
  'Google Inc. (Samsung Electronics Co., Ltd.)',
  'Google Inc.(NVIDIA)',
  'Imagination Technologies',
  'Intel',
  'Intel Inc.',
  'Intel Open Source Technology Center',
  'Mesa',
  'Mesa/X.org',
  'NA',
  'NVIDIA Corporation',
  'Not available',
  'Qualcomm',
  'SBdTWBB1Dr',
  'Samsung Electronics Co., Ltd.',
  'eHzMdi0sbt',
  'r0a05FKN',
]

export const UNMASKED_RENDERERS = [
  '3672',
  'AMD Radeon R9 M370X OpenGL Engine',
  'AMD Radeon(TM) R2 Graphics',
  'ANGLE (0x05404C42, Parallels Display Adapter (WDDM) (0x00000000) Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (AMD Radeon R7 430 Direct3D11 vs_5_0 ps_5_0)',
  'ANGLE (AMD, AMD PITCAIRN, OpenGL 4.5)',
  'ANGLE (AMD, AMD Radeon (TM) Graphics (0x000015E7) Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (AMD, AMD Radeon 780M Graphics (0x000015BF) Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (AMD, NAVI24 (navi24 LLVM 15.0.7 DRM 3.54 6.6.26-1-MANJARO), OpenGL 4.6)',
  'ANGLE (AMD, Radeon (TM) RX 470 Graphics (0x000067DF) Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (AMD, Radeon RX550/550 Series Direct3D11 vs_5_0 ps_5_0, D3D11-27.20.14501.18003)',
  'ANGLE (ARM, Mali-G51, OpenGL ES 3.2)',
  'ANGLE (ATI Technologies Inc., AMD Radeon Pro 5300M OpenGL Engine, OpenGL 4.1)',
  'ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Max, Unspecified Version)',
  'ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Pro, Unspecified Version)',
  'ANGLE (Google, Vulkan 1.2.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)',
  'ANGLE (Google, Vulkan 1.2.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver-5.0.0)',
  'ANGLE (Imagination Technologies, PowerVR B-Series BXM-8-256, OpenGL ES 3.2)',
  'ANGLE (Intel Inc., Intel HD Graphics 3000 OpenGL Engine, OpenGL 3.3)',
  'ANGLE (Intel Open Source Technology Center, Mesa DRI Intel(R) HD Graphics 4600 (HSW GT2), OpenGL 4.5)',
  'ANGLE (Intel(R) HD Graphics Direct3D11 vs_4_1 ps_4_1)',
  'ANGLE (Intel(R) Iris(R) Xe Graphics Direct3D11 vs_5_0 ps_5_0)',
  'ANGLE (Intel, ANGLE Metal Renderer: Intel(R) Iris(TM) Plus Graphics, Unspecified Version)',
  'ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (Intel, Mesa Intel(R) Xe Graphics (TGL GT2), OpenGL 4.6)',
  'ANGLE (Intel, Vulkan 1.3.267 (Intel(R) UHD Graphics (TGL GT2) (0x00009A78)), Intel open-source Mesa driver)',
  'ANGLE (Mesa, Apple M1 Pro (G13S C0), OpenGL ES 3.1)',
  'ANGLE (Mesa, NV166, OpenGL 4.3)',
  'ANGLE (Mesa/X.org, llvmpipe (LLVM 15.0.6 128 bits), OpenGL 4.5)',
  'ANGLE (Mesa/X.org, llvmpipe (LLVM 15.0.6 256 bits), OpenGL 4.5)',
  'ANGLE (Microsoft Corporation, D3D12 (Intel(R) UHD Graphics), OpenGL 4.1)',
  'ANGLE (Microsoft, Microsoft Basic Render Driver (0x0000008C) Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (Microsoft, Microsoft Basic Render Driver Direct3D11 vs_5_0 ps_5_0), or similar',
  'ANGLE (NVIDIA Corporation, GeForce GTX 1050/PCIe/SSE2, OpenGL 4.5 core)',
  'ANGLE (NVIDIA Corporation, Quadro P620/PCIe/SSE2, OpenGL 4.5.0)',
  'ANGLE (NVIDIA GeForce 210 Direct3D9Ex vs_3_0 ps_3_0)',
  'ANGLE (NVIDIA GeForce GTX 670 Direct3D9Ex vs_0_0 ps_2_0)',
  'ANGLE (NVIDIA Quadro 2000M Direct3D11 vs_5_0 ps_5_0)',
  'ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)',
  'ANGLE (NVIDIA, NVIDIA Quadro K2000 Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (NVIDIA, NVIDIA RTX A4000 (0x000024B0) Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (NVIDIA, NVIDIA T1000 8GB (0x00001FF0) Direct3D11 vs_5_0 ps_5_0, D3D11)',
  'ANGLE (NVIDIA, Vulkan 1.3.277 (NVIDIA NVIDIA GeForce GTX 1050 Ti (0x00001C82)), NVIDIA)',
  'ANGLE (Qualcomm, Adreno (TM) 512, OpenGL ES 3.2)',
  'ANGLE (Samsung Xclipse 920) on Vulkan 1.3.231',
  'Adreno (TM)',
  'Apple GPU',
  'Apple M1',
  'Apple M1, or similar',
  'Benim Kart adi',
  'GeForce GTX 480, or similar',
  'GeForce GTX 980, or similar',
  'Google SwiftShader',
  'Intel HD Graphics 2295 OpenGL Engine',
  'Intel Iris OpenGL Engine',
  'Intel UHD Graphics 620',
  'Intel(R) HD Graphics',
  'Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49)',
  'Mali-G51, or similar',
  'Mali-T720',
  'Mali-T830',
  'Mesa DRI Intel HD Graphics 630 (Kaby Lake GT2)',
  'Mesa DRI Intel(R) Ivybridge Mobile',
  'NA',
  'NVIDIA GeForce GTX 480, or similar',
  'NVIDIA GeForce GTX 980/PCIe/SSE2',
  'Not available',
  'PowerVR Rogue GE8300',
  'PowerVR Rogue GE8320',
  'RUxg3Ehv',
  'Radeon HD 3200 Graphics',
  'Radeon HD 3200 Graphics, or similar',
  'Radeon R9 200 Series, or similar',
  'llvmpipe, or similar',
]
